name: dhh-comm-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy
  - pandas
  - pillow
  - opencv
  - pip:
    - --force-reinstall
    - streamlit==1.43.1
    - deepface
    - flask
    - flask-cors
    - tensorflow
    - keras
    - mtcnn
    - retina-face
    - plotly
    - pyautogui 